apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: prom
  labels:
    app: prom
spec:
  type: ClusterIP
  selector:
    app: prom
  ports:
    - port: 8081
      targetPort: 8081
      name: web
      protocol: TCP