apiVersion: v1
kind: Pod
metadata:
  name: prom-pod
  labels:
    app: prom
  namespace: prom
spec:
  containers:
    - name: prom-container
      image: mobarak9239/prom
      ports:
        - containerPort: 8081