apiVersion: v1
kind: Pod
metadata:
  name: example-app
  labels:
    app: example-app
  namespace: prom
spec:
  containers:
    - name: prom-container
      image: mobarak9239/prom:1
      ports:
        - containerPort: 8081