apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: prom
  labels:
    app: example-app
spec:
  type: ClusterIP
  selector:
    app: example-app
  ports:
    - port: 8081
      targetPort: 8081
      name: web
      protocol: TCP