apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  namespace: prom
  name: exporter-servicemonitor
spec:
  endpoints:
    - interval: 10s
      port: web
  selector:
    matchLabels:
      app: prom